---

- hosts: all # target all hosts in the inventory
  become: true # allow elevated privileges
  tasks:
    - name: install apache and php
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
    
