---

- hosts: all # target all hosts in the inventory
  become: true # allow elevated privileges
  tasks:
    - name: Update repository index
      apt:
        update_cache: yes
      when: ansible_distribution in  ["Debian", "Ubuntu"] # Run for only Ubuntu servers

    - name: Install apache2 package
      apt: # use the apt module
        name: apache2
        state: latest # ensure that the latest version of the package is installed
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Update repository index for CentOS
      dnf:
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Install httpd package for CentOS
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Add php support for apache on CentOS
      dnf:
        name: php
        state: latest
      when: ansible_distribution == "CentOS"
