---

- hosts: all # target all hosts in the inventory
  become: true # allow elevated privileges
  tasks: 
    - name: Install apache2 and php packages
      apt: # use the apt module
        name:
          - apache2
          - libapache2-mod-php
        state: latest # ensure that the latest version of the package is installed
        update_cache: true
      when: ansible_distribution in ["Debian", "Ubuntu"] 

    - name: Install httpd and php packages for CentOS
      dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: true
      when: ansible_distribution == "CentOS"
