---

- hosts: all
  become: true
  pre_tasks: 
    - name: Update repository index (CentOS)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: Update repository index (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base 

- hosts: workstations
  become: true
  roles:
    - workstations 

- hosts: web_servers
  become: true
  roles:
    - workstations

- hosts: db_servers
  become: true
  roles:
    - db_servers

